---
title: "What's Next is All Anyone Needs to Begin"
---

### The Past is Prologue

Throughout the many experiences during my undergraduate degree, I've learned a lot. 
Its just as important to remember what we've learned as it is to look forward to see what we can learn next.
I learned how communication impacts results, especially through sports analytics projects, where technical work must be explained in the terms of the sport.
I learned about professionalism, through my capstone project where we worked with a client whose technical ideas we did not necessarily agree with.
I learned the value of proper project and time management through my many group projects, where having the right people working on the right tasks ultimately dictated results.
And most importantly, I learned that there's always a bigger fish: as much as I've learned so far, there will always be more to learn.
With these ideas in mind, its worth considering how my immediate next steps continue the development of these skills and continue my learning.

### GroupWAR

The GroupWAR project is something I intend to continue to build out in the public domain. The three main facets are to present it at a conference, build out a website and develop the idea for basketball.
Continuing this project allows me to continue to sharpen my communication skills, as I turn such complex ideas into visuals and reports on players.
If anyone is interested more in understanding this project or the related work, please reach out!

### Continuing at PG

The next step in my professional career is returning to Posterity Group as a full time consultant. 
There, I will be given the opportunity to manage projects, and continue to work with clients, allowing me to further develop my project management and professionalism skills.

### Thank You

That's all for now! So long, and thanks for all the fish! May they continue to get bigger...